# Chi-squared test

A chi-squared test exists to test the association between two categorical variables.

We are ging to use another example from AGRESTI and FINLAY (2012). In this example, we want to see if party association has any gender bias. Therefore our hypothesis are: <br><br>

H0 : Gender does not influenciate political prerfernces<br>
H1: Gender influenciates political preferences<br><br>


First we need to form a contingency table in which each row is the independent variable and each column is the dependent variable.
We are going to use the contingency table (e.g. already grouped) from the book:


In [1]:
import numpy as np
import pandas as pd
from scipy import stats

In [3]:
gender = ['women', 'men', 'total']

df = {'democrats' : [573, 386, 959],
       'independent': [516, 475, 991],
       'republicans': [422, 399, 821],
       'total': [1511, 1260, 2771]}

df = pd.DataFrame(df, index = gender)
df

democrats  independent  republicans  total
women        573          516          422   1511
men          386          475          399   1260
total        959          991          821   2771

In [4]:
# Let's do the test

#first, getting the totals:
df = df.iloc[:2]

data = df[['democrats', 'independent', 'republicans']].to_numpy()
data

array([[573, 516, 422],
       [386, 475, 399]])

In [6]:
#Chi-suqared test

chi2_stat, p_val, dof, ex = stats.chi2_contingency(data)

print("===Chi2 Stat===")
print(chi2_stat)
print("\n")
print("===Degrees of Freedom===")
print(dof)
print("\n")
print("===P-Value===")
print(p_val)
print("\n")
print("===Contingency Table===")
print(ex)

===Chi2 Stat===
16.201726038971145


===Degrees of Freedom===
2


===P-Value===
0.0003032772908939342


===Contingency Table===
[[522.93359798 540.38289426 447.68350776]
 [436.06640202 450.61710574 373.31649224]]


Our p-value is lower than 0.05, which means that we can reject the null hypothesis and assume that there is a gender bias in political preferences